name: Brush
version: '${project.version}'
main: me.nesox.brush.Brush
api-version: 1.16
authors: [ Nes0x ]
depend: [WorldGuard]

commands:
  brushes:
    permission: brush.give


permissions:
  brush.give:
    description: Permisja do komendy /brushes
    default: op